# rename this to settings.yaml
client_config_backend: settings
client_config:
  client_id: your-google-drive-api-client-id
  client_secret: your-google-drive-api-client-secret

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

oauth_scope: 
  - https://www.googleapis.com/auth/drive.file

fb_access_token:
  your-facebook-access-token
